### ISSUE TITLE
Progress bar issue

### ISSUE THREAD

**Issue by febryce** [astroncc/astroncc#9]
Hi,

I can't choose a specific time in the progress bar. But it works on Shorts vidéo.

I uninstalled the application but the issue persists.

Do you have a solution to this problem ?

Thanks for ur help

![Screenshot_20240107_014708_ASTRON](https://github.com/astroncc/astron_app/assets/103374867/25a8d1d1-4aa3-4a8c-b82f-c56b0dabcc00)

**Comment by astroncc** [comment]
We have identified the issue, and it will be fixed through an update soon.

**Comment by febryce** [comment]
> We have identified the issue, and it will be fixed through an update soon.

Oh ok thank you !
